name: Build & Release Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ' 3.32.8'   # change if you use another version

      - name: Install dependencies
        run: flutter pub get

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep ^version: pubspec.yaml | awk '{print $2}' | tr -d '\r')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build release APK
        run: flutter build apk --release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: FlashSOS ${{ env.VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: FlashSOS-${{ env.VERSION }}.apk
          asset_content_type: application/vnd.android.package-archive
